import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { useEffect, useState } from 'react'
import makeRequest from '@/utils/Fetcher'

const inter = Inter({ subsets: ['latin'] })

const Home = () => {
  const [data, setData] = useState([]);
  useEffect(() => {
    // const getData = async () => {
    //   try {
    //     const response = await axios.get("http://127.0.0.1:8000/api/categories");
    //     setData(response.data['hydra:member']);
    //   }catch(err) {
    //     console.log("Error trying to fetch API => " + err);
    //   }
    // }

    // getData();
    const data = async () => {
      const d = await makeRequest({
        method: "get",
        url: "http://127.0.0.1:8000/api/categories",
        data: ""
      });
      setData(d);
    }

    data();
    
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {
          data.map((d, index) => (
            <p key={index}>{d.name}</p>
          ))
        }
      </main>
    </>
  )
}

export default Home;