import Head from "next/head";
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button } from 'primereact/button';
import { Carousel } from 'primereact/carousel';
//theme
import "primereact/resources/themes/lara-light-indigo/theme.css";

//core
import "primereact/resources/primereact.min.css";

const inter = Inter({ subsets: ['latin'] })

const test = () => {

    
    const itemTemplate = (product) => {
        return (
            <p>{product}</p>
        );

    }

    const responsiveOptions = [
        {
            breakpoint: '1199px',
            numVisible: 1,
            numScroll: 1
        },
        {
            breakpoint: '991px',
            numVisible: 2,
            numScroll: 1
        },
        {
            breakpoint: '767px',
            numVisible: 1,
            numScroll: 1
        }
    ];
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <p>Hello</p>
                <Button>Test</Button>
                <Carousel value={["A", "B", "C", "D", "E", "F"]} responsiveOptions={responsiveOptions} itemTemplate={itemTemplate}></Carousel>
            </main>

        </>
    )
}

export default test;